#############################################################################
# Makefile for building: cpaint-qt
# Generated by qmake (2.01a) (Qt 4.8.6) on: Sat Aug 2 22:51:33 2014
# Project:  cpaint-qt.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile cpaint-qt.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT $(DEFINES) --std=c++11
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = calculator.cpp \
		graph.cpp \
		graphpair.cpp \
		inputedit.cpp \
		main.cpp \
		parser.cpp \
		uibuilders.cpp moc_graph.cpp \
		moc_graphpair.cpp \
		moc_inputedit.cpp
OBJECTS       = calculator.o \
		graph.o \
		graphpair.o \
		inputedit.o \
		main.o \
		parser.o \
		uibuilders.o \
		moc_graph.o \
		moc_graphpair.o \
		moc_inputedit.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		cpaint-qt.pro
QMAKE_TARGET  = cpaint-qt
DESTDIR       = 
TARGET        = cpaint-qt

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: cpaint-qt.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile cpaint-qt.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile cpaint-qt.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/cpaint-qt1.0.0 || $(MKDIR) .tmp/cpaint-qt1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/cpaint-qt1.0.0/ && $(COPY_FILE) --parents calculator.h common.h diff.h graph.h graphpair.h inputedit.h parser.h uibuilders.h .tmp/cpaint-qt1.0.0/ && $(COPY_FILE) --parents calculator.cpp graph.cpp graphpair.cpp inputedit.cpp main.cpp parser.cpp uibuilders.cpp .tmp/cpaint-qt1.0.0/ && (cd `dirname .tmp/cpaint-qt1.0.0` && $(TAR) cpaint-qt1.0.0.tar cpaint-qt1.0.0 && $(COMPRESS) cpaint-qt1.0.0.tar) && $(MOVE) `dirname .tmp/cpaint-qt1.0.0`/cpaint-qt1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/cpaint-qt1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_graph.cpp moc_graphpair.cpp moc_inputedit.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_graph.cpp moc_graphpair.cpp moc_inputedit.cpp
moc_graph.cpp: calculator.h \
		parser.h \
		diff.h \
		common.h \
		graph.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) graph.h -o moc_graph.cpp

moc_graphpair.cpp: graph.h \
		calculator.h \
		parser.h \
		diff.h \
		common.h \
		graphpair.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) graphpair.h -o moc_graphpair.cpp

moc_inputedit.cpp: inputedit.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) inputedit.h -o moc_inputedit.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

calculator.o: calculator.cpp calculator.h \
		parser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calculator.o calculator.cpp

graph.o: graph.cpp graph.h \
		calculator.h \
		parser.h \
		diff.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graph.o graph.cpp

graphpair.o: graphpair.cpp graphpair.h \
		graph.h \
		calculator.h \
		parser.h \
		diff.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphpair.o graphpair.cpp

inputedit.o: inputedit.cpp inputedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inputedit.o inputedit.cpp

main.o: main.cpp graph.h \
		calculator.h \
		parser.h \
		diff.h \
		common.h \
		graphpair.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

parser.o: parser.cpp parser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parser.o parser.cpp

uibuilders.o: uibuilders.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uibuilders.o uibuilders.cpp

moc_graph.o: moc_graph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graph.o moc_graph.cpp

moc_graphpair.o: moc_graphpair.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphpair.o moc_graphpair.cpp

moc_inputedit.o: moc_inputedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_inputedit.o moc_inputedit.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

